"""
Daily portfolio brief email sender.
Run with: python -m scanner.send_brief
"""
import sys
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from zoneinfo import ZoneInfo
from config import get_secret
from scanner.daily_brief import build_full_brief

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger(__name__)

SIGNAL_COLOR = {
    "BUY": "#22c55e", "WATCH CAREFULLY": "#3b82f6",
    "HOLD": "#eab308", "REDUCE": "#f97316", "EXIT": "#ef4444",
}


def _pnl_color(pnl: float) -> str:
    return "#22c55e" if pnl >= 0 else "#ef4444"


def _position_html(p: dict) -> str:
    if "error" in p:
        return f"<p><strong>{p['ticker']}</strong> — error: {p['error']}</p>"

    sig_color = SIGNAL_COLOR.get(p["signal"], "#6b7280")
    pnl_color = _pnl_color(p["pnl_pct"])
    news_items = "".join(f"<li style='color:#9ca3af'>{h}</li>" for h in p["headlines"][:3]) if p["headlines"] else "<li style='color:#9ca3af'>No recent headlines</li>"

    return f"""
<div style="background:#1e293b;border-radius:8px;padding:16px;margin-bottom:16px;">
  <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
    <span style="font-size:1.2em;font-weight:700;color:#f1f5f9">{p['ticker']}</span>
    <span style="background:{sig_color};color:#fff;padding:2px 10px;border-radius:12px;font-size:0.85em;font-weight:600">
      {p['signal_emoji']} {p['signal']} &nbsp;{p['score']:.0f}/100
    </span>
  </div>

  <table style="width:100%;color:#cbd5e1;font-size:0.9em;margin-bottom:10px">
    <tr>
      <td>Entry</td><td><strong style="color:#f1f5f9">${p['entry_price']:.2f}</strong></td>
      <td>Current</td><td><strong style="color:#f1f5f9">${p['current_price']:.2f}</strong></td>
      <td>P&amp;L</td><td><strong style="color:{pnl_color}">{p['pnl_pct']:+.1f}% (${p['pnl_dollars']:+,.0f})</strong></td>
    </tr>
    <tr style="color:#94a3b8">
      <td>Stop</td><td>${p['stop']:.2f} <span style="color:#ef4444">({p['pct_to_stop']:+.1f}%)</span></td>
      <td>Target 1</td><td>${p['target1']:.2f} <span style="color:#22c55e">({p['pct_to_t1']:+.1f}%)</span></td>
      <td>Target 2</td><td>${p['target2']:.2f} <span style="color:#22c55e">({p['pct_to_t2']:+.1f}%)</span></td>
    </tr>
  </table>

  <div style="background:#0f172a;border-radius:6px;padding:10px;margin-bottom:8px;color:#e2e8f0;font-size:0.9em;line-height:1.5">
    💡 {p['ai_summary']}
  </div>

  <ul style="margin:4px 0;padding-left:18px;font-size:0.82em">{news_items}</ul>
</div>
"""


def _account_html(account: dict) -> str:
    pos_html = "".join(_position_html(p) for p in account["positions"]) if account["positions"] else \
        "<p style='color:#9ca3af'>No open positions.</p>"

    return f"""
<div style="margin-bottom:32px">
  <h2 style="color:#94a3b8;border-bottom:1px solid #334155;padding-bottom:8px;margin-bottom:16px">
    {account['label']}
  </h2>
  <p style="color:#cbd5e1;margin-bottom:16px">
    Portfolio Value: <strong style="color:#f1f5f9">${account['portfolio_value']:,.2f}</strong>
    &nbsp;|&nbsp; Buying Power: <strong style="color:#f1f5f9">${account['buying_power']:,.2f}</strong>
  </p>
  {pos_html}
</div>
"""


def build_html_email(accounts: list[dict], date_str: str) -> str:
    accounts_html = "".join(_account_html(a) for a in accounts)
    return f"""
<!DOCTYPE html>
<html>
<body style="background:#0f172a;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#f1f5f9;padding:24px;max-width:700px;margin:0 auto">
  <h1 style="color:#f1f5f9;margin-bottom:4px">📊 Daily Portfolio Brief</h1>
  <p style="color:#64748b;margin-bottom:28px">{date_str} ET</p>
  {accounts_html}
  <p style="color:#475569;font-size:0.8em;border-top:1px solid #1e293b;padding-top:16px">
    Generated by your Stock Advisor app. Not financial advice.
  </p>
</body>
</html>
"""


def send_email(subject: str, html_body: str) -> None:
    from_addr = get_secret("EMAIL_FROM")
    password  = get_secret("EMAIL_PASSWORD")
    to_addr   = get_secret("EMAIL_TO")

    if not all([from_addr, password, to_addr]):
        raise RuntimeError("EMAIL_FROM, EMAIL_PASSWORD, and EMAIL_TO must be set in secrets.")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = from_addr
    msg["To"]      = to_addr
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(from_addr, password)
        server.sendmail(from_addr, to_addr, msg.as_string())


def run_send_brief() -> None:
    et = datetime.now(ZoneInfo("America/New_York"))
    date_str = et.strftime("%A, %B %d %Y — %I:%M %p")
    log.info(f"Building daily brief for {date_str}...")

    accounts = build_full_brief()
    total_positions = sum(len(a["positions"]) for a in accounts)
    log.info(f"Built briefs for {total_positions} positions across {len(accounts)} accounts")

    html = build_html_email(accounts, date_str)
    subject = f"📊 Portfolio Brief — {et.strftime('%b %d, %Y')}"

    log.info("Sending email...")
    send_email(subject, html)
    log.info("Email sent successfully.")


if __name__ == "__main__":
    run_send_brief()
